if(ANDROID)
    set(OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/bin/android/${CMAKE_ANDROID_API})
elseif(IOS)
    set(OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/bin/ios/${CMAKE_ANDROID_API})

else()
    if(WIN32)
        set(USE_GUI ON)
    endif()

    IF(CMAKE_SIZEOF_VOID_P EQUAL 8)
        SET(ARCH_BITS 64)
    ELSE()
        SET(ARCH_BITS 32)
    ENDIF()

    set(OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/bin/${CMAKE_SYSTEM_NAME}_${ARCH_BITS})
endif()



message("11 cmake_output_path CMAKE_SYSTEM_NAME=" ${CMAKE_SYSTEM_NAME})
message("22 OUTPUT_DIRECTORY:" ${OUTPUT_DIRECTORY})
SET(OUTPUT_DIRECTORY_DEBUG ${OUTPUT_DIRECTORY}_debug)
SET(OUTPUT_DIRECTORY_RELEASE ${OUTPUT_DIRECTORY}_release)

SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${OUTPUT_DIRECTORY})
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${OUTPUT_DIRECTORY})
SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${OUTPUT_DIRECTORY})

SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${OUTPUT_DIRECTORY_DEBUG})
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${OUTPUT_DIRECTORY_DEBUG})
SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG ${OUTPUT_DIRECTORY_DEBUG})

SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${OUTPUT_DIRECTORY_RELEASE})
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${OUTPUT_DIRECTORY_RELEASE})
SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE ${OUTPUT_DIRECTORY_RELEASE})
#这里供子类调用
set(ChangeOutPath TRUE)